default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ecokazik_development

test:
  <<: *default
  database: ecokazik_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Base de données pour Solid Queue (Rails 8)
queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Base de données pour Action Cable (si jamais tu l'utilises)
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
